---
title: "Stat 139 Final Project"
author: "Group"
date: "December 14, 2022"
geometry: margin=2.45cm
output: pdf_document

---

```{r}
library(tidyverse)
set.seed(139)
data <- read.csv('MERGED2018_19_PP.csv')
data <- data[data$DISTANCEONLY == 0, ]
data <- as.data.frame(data)
```

Data wrangling
```{r}
# "Traditional" universities - report both 'ADM_RATE' and 'SAT_AVG' 
# "Non-traditional" universities - report one or neither of 'ADM_RATE' and 'SAT_AVG' 

both_cols <- c('MD_EARN_WNE_P6', 'HIGHDEG', 'REGION', 'UGDS_WHITE', 'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN', 'UGDS_AIAN', 'UGDS_NHPI', 'C150_4', 'C150_L4', 'UGDS', 'UGDS_MEN', 'NPT4_PUB', 'NPT4_PRIV', 'PCIP04', 'PCIP05', 'PCIP09', 'PCIP11', 'PCIP12', 'PCIP14', 'PCIP23', 'PCIP26', 'PCIP27', 'PCIP38', 'PCIP42', 'PCIP45', 'PCIP50', 'PCIP51', 'PCIP52', 'PCIP54')
traditional_cols <- c('ADM_RATE', 'SAT_AVG')

data <- data[, c(both_cols, traditional_cols)]
data[data == ""] = NA
data[data == "NULL"] = NA
data$C150 <- coalesce(data$C150_4, data$C150_L4)
data$NPT4 <- coalesce(data$NPT4_PUB, data$NPT4_PRIV)
data <- subset(data, select = -c(C150_4,C150_L4, NPT4_PUB, NPT4_PRIV))
data <- as.data.frame(data)

completeFun <- function(data, desiredCols) {
  completeVec <- complete.cases(data[, desiredCols])
  return(data[completeVec, ])
}

data <- completeFun(data, c('MD_EARN_WNE_P6', 'HIGHDEG', 'REGION', 'UGDS_WHITE', 'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN', 'UGDS_AIAN', 'UGDS_NHPI', 'C150', 'UGDS', 'UGDS_MEN', 'NPT4', 'PCIP04', 'PCIP05', 'PCIP09', 'PCIP11', 'PCIP12', 'PCIP14', 'PCIP23', 'PCIP26', 'PCIP27', 'PCIP38', 'PCIP42', 'PCIP45', 'PCIP50', 'PCIP51', 'PCIP52', 'PCIP54'))
nrow(data)

traditional <- data[!is.na(data$ADM_RATE) & !is.na(data$SAT_AVG), ]
nrow(traditional)
traditional <- sapply(traditional, as.numeric)
traditional <- as.data.frame(traditional)

nontraditional <- data[is.na(data$ADM_RATE) | is.na(data$SAT_AVG), ]
nontraditional <- subset(nontraditional, select = -c(ADM_RATE, SAT_AVG))
nrow(nontraditional)
nontraditional <- sapply(nontraditional, as.numeric)
nontraditional <- as.data.frame(nontraditional)


traditional$HIGHDEG <-factor(traditional$HIGHDEG, levels=0:4, labels=c("Non-degree granting", "Certificate degree", "Associate degree", "Bachelor's degree", "Graduate degree"))
traditional$REGION <- factor(traditional$REGION, levels=0:9, labels=c("U.S. Service Schools", "New England", "Mid East", "Great Lakes", "Plains", "Southeast", "Southwest", "Rocky Mountains", "Far West", "Outlying Areas"))

nontraditional$HIGHDEG <-factor(nontraditional$HIGHDEG, levels=0:4, labels=c("Non-degree granting", "Certificate degree", "Associate degree", "Bachelor's degree", "Graduate degree"))
nontraditional$REGION <- factor(nontraditional$REGION, levels=0:9, labels=c("U.S. Service Schools", "New England", "Mid East", "Great Lakes", "Plains", "Southeast", "Southwest", "Rocky Mountains", "Far West", "Outlying Areas"))

data <- subset(data, select = -c(ADM_RATE, SAT_AVG))

# data: all universities, no SAT/ADM_RATE predictors
# traditional: traditional universities, including SAT/ADM_RATE predictors
# non-traditional: non-traditional universities, no SAT/ADM_RATE predictors 
```

Lawrence
```{r}

```

Charu
```{r}
library(xtable)
# transform proportions to percentages
traditional$UGDS_ASIAN <- traditional$UGDS_ASIAN * 100
traditional$PCIP11 <- traditional$PCIP11 * 100
traditional$PCIP14 <- traditional$PCIP14 * 100
traditional$PCIP27 <- traditional$PCIP27 * 100
traditional$PCIP26 <- traditional$PCIP26 * 100

# Asian percent as predictor
lm.asian <- lm(log(MD_EARN_WNE_P6) ~ UGDS_ASIAN, data=traditional)
summary(lm.asian)
xtable(summary(lm.asian))
# Verification of assumptions
plot(log(MD_EARN_WNE_P6) ~ UGDS_ASIAN, data=traditional)
plot(lm.asian$residuals ~ lm.asian$fitted.values)
qqnorm(lm.asian$residuals)
qqline(lm.asian$residuals)

# Asian percent and STEM majors as predictors
lm.asian.stem <- lm(log(MD_EARN_WNE_P6) ~ UGDS_ASIAN + PCIP11 + PCIP14 + PCIP27 + PCIP26, data=traditional)
summary(lm.asian.stem)
xtable(summary(lm.asian.stem))
# Verification of assumptions
plot(lm.asian.stem$residuals ~ lm.asian.stem$fitted.values)
qqnorm(lm.asian.stem$residuals)
qqline(lm.asian.stem$residuals)

# STEM majors as predictors
lm.stem <- lm(log(MD_EARN_WNE_P6) ~ PCIP11 + PCIP14 + PCIP27 + PCIP26, data=traditional)
summary(lm.stem)
xtable(summary(lm.stem))
# Verification of assumptions
plot(lm.stem$residuals ~ lm.stem$fitted.values)
qqnorm(lm.stem$residuals)
qqline(lm.stem$residuals)
```

